/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedConversationsRouteImport } from './routes/_authed.conversations'
import { Route as AuthedDashboardRouteImport } from './routes/_authed.dashboard'
import { Route as AuthedConversationsIndexRouteImport } from './routes/_authed.conversations.index'
import { Route as AuthedConversationsConversationIdRouteImport } from './routes/_authed.conversations.$conversationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedConversationsRoute = AuthedConversationsRouteImport.update({
  id: '/conversations',
  path: '/conversations',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedConversationsIndexRoute =
  AuthedConversationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedConversationsRoute,
  } as any)
const AuthedConversationsConversationIdRoute =
  AuthedConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthedConversationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/conversations': typeof AuthedConversationsRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/conversations/$conversationId': typeof AuthedConversationsConversationIdRoute
  '/conversations/': typeof AuthedConversationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/conversations/$conversationId': typeof AuthedConversationsConversationIdRoute
  '/conversations': typeof AuthedConversationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/conversations': typeof AuthedConversationsRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/conversations/$conversationId': typeof AuthedConversationsConversationIdRoute
  '/_authed/conversations/': typeof AuthedConversationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/conversations'
    | '/dashboard'
    | '/conversations/$conversationId'
    | '/conversations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/conversations/$conversationId'
    | '/conversations'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/_authed/conversations'
    | '/_authed/dashboard'
    | '/_authed/conversations/$conversationId'
    | '/_authed/conversations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/conversations': {
      id: '/_authed/conversations'
      path: '/conversations'
      fullPath: '/conversations'
      preLoaderRoute: typeof AuthedConversationsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/conversations/': {
      id: '/_authed/conversations/'
      path: '/'
      fullPath: '/conversations/'
      preLoaderRoute: typeof AuthedConversationsIndexRouteImport
      parentRoute: typeof AuthedConversationsRoute
    }
    '/_authed/conversations/$conversationId': {
      id: '/_authed/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/conversations/$conversationId'
      preLoaderRoute: typeof AuthedConversationsConversationIdRouteImport
      parentRoute: typeof AuthedConversationsRoute
    }
  }
}

interface AuthedConversationsRouteChildren {
  AuthedConversationsConversationIdRoute: typeof AuthedConversationsConversationIdRoute
  AuthedConversationsIndexRoute: typeof AuthedConversationsIndexRoute
}

const AuthedConversationsRouteChildren: AuthedConversationsRouteChildren = {
  AuthedConversationsConversationIdRoute:
    AuthedConversationsConversationIdRoute,
  AuthedConversationsIndexRoute: AuthedConversationsIndexRoute,
}

const AuthedConversationsRouteWithChildren =
  AuthedConversationsRoute._addFileChildren(AuthedConversationsRouteChildren)

interface AuthedRouteChildren {
  AuthedConversationsRoute: typeof AuthedConversationsRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedConversationsRoute: AuthedConversationsRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
